// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mhr-locations": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns paginated MHR location mappings with optional filters. Include export query parameter to download CSV.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Get paginated MHR location mappings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Items per page (default: 10, max: 100)",
                        "name": "perPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by rink name (partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by province (partial match)",
                        "name": "province",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Export as CSV when present (any non-empty value)",
                        "name": "export",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MHRLocResult"
                        }
                    }
                }
            }
        },
        "/scrape": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Starts scraping for specified site or all enabled sites. Sites already being scraped are skipped. Returns 409 only if ALL requested sites are already running.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraping"
                ],
                "summary": "Trigger scraping for site(s)",
                "parameters": [
                    {
                        "description": "Scraping request parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ScrapeRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted, returns job status with sites_started and optionally sites_skipped",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "All requested sites are already being scraped",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/scrape/status": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns current scraping status for all configured sites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraping"
                ],
                "summary": "Get scraping status for all sites",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.ScrapeStatus"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/scrape/status/{site}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns current scraping status for the specified site",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraping"
                ],
                "summary": "Get scraping status for a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site name",
                        "name": "site",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScrapeStatus"
                        }
                    },
                    "404": {
                        "description": "Site not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/site-locations": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns paginated site location mappings for a given site with optional pagination parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Get paginated site location mappings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site name",
                        "name": "site",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter locations starting with this value",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Items per page (default: 10, max: 100)",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SiteLocResult"
                        }
                    }
                }
            }
        },
        "/sites-config/{id}/toggle": {
            "post": {
                "description": "Toggles the enabled status of a site configuration. If enabled is NULL, sets to true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SitesConfig"
                ],
                "summary": "Toggle site configuration enabled status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site Config ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SitesConfigResponse"
                        }
                    },
                    "404": {
                        "description": "Site config not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ScrapeRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "Date in YYYY-MM-DD format (optional)",
                    "type": "string"
                },
                "site": {
                    "description": "Site name (empty for all enabled sites)",
                    "type": "string"
                },
                "workers": {
                    "description": "Number of workers (optional, default 1)",
                    "type": "integer"
                }
            }
        },
        "main.ScrapeStatus": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message if failed",
                    "type": "string"
                },
                "is_due_for_scraping": {
                    "description": "Whether site is due for scraping",
                    "type": "boolean"
                },
                "last_scraped_at": {
                    "description": "From sites_config",
                    "type": "string"
                },
                "scrape_frequency": {
                    "description": "Frequency in hours",
                    "type": "integer"
                },
                "site": {
                    "type": "string"
                },
                "started_at": {
                    "description": "When scraping started",
                    "type": "string"
                },
                "status": {
                    "description": "idle, running, completed, failed",
                    "type": "string"
                }
            }
        },
        "model.Location": {
            "type": "object",
            "properties": {
                "address1": {
                    "type": "string"
                },
                "address2": {
                    "type": "string"
                },
                "all_sheets_count": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "logo_url": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province_id": {
                    "type": "integer"
                },
                "recording_hours_local": {
                    "type": "string"
                },
                "total_surfaces": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                },
                "venue_status": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "model.Surface": {
            "type": "object",
            "properties": {
                "closed_from": {
                    "type": "integer"
                },
                "coming_soon": {
                    "type": "boolean"
                },
                "first_media_date": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "location_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "orderIndex": {
                    "type": "integer"
                },
                "sports": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "venue_id": {
                    "type": "integer"
                }
            }
        },
        "models.MHRLocResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MhrLocation"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.MhrLocation": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "aka": {
                    "type": "string"
                },
                "home_teams": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                },
                "linkedSurface": {
                    "$ref": "#/definitions/model.Surface"
                },
                "liveBarnLocation": {
                    "$ref": "#/definitions/model.Location"
                },
                "livebarn_installed": {
                    "type": "boolean"
                },
                "livebarn_location_id": {
                    "type": "integer"
                },
                "livebarn_surface_id": {
                    "type": "integer"
                },
                "mhr_id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "rink_name": {
                    "type": "string"
                },
                "streaming": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "models.SiteLoc": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "linkedSurface": {
                    "$ref": "#/definitions/model.Surface"
                },
                "liveBarnLocation": {
                    "$ref": "#/definitions/model.Location"
                },
                "location": {
                    "type": "string"
                },
                "location_id": {
                    "type": "integer"
                },
                "match_type": {
                    "type": "string"
                },
                "scraping_error": {
                    "type": "string"
                },
                "scraping_started_at": {
                    "type": "string"
                },
                "scraping_status": {
                    "type": "string"
                },
                "site": {
                    "type": "string"
                },
                "surface": {
                    "type": "string"
                },
                "surface_id": {
                    "type": "integer"
                }
            }
        },
        "models.SiteLocResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SiteLoc"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.SitesConfigResponse": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "games_imported": {
                    "type": "integer"
                },
                "games_scraped": {
                    "type": "integer"
                },
                "home_team": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_scraped_at": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "parser_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "parser_type": {
                    "type": "string"
                },
                "scrape_frequency_hours": {
                    "type": "integer"
                },
                "scraping_error": {
                    "type": "string"
                },
                "scraping_started_at": {
                    "type": "string"
                },
                "scraping_status": {
                    "type": "string"
                },
                "site_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "gosession",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Surface API",
	Description:      "API for managing hockey rink schedules, surfaces, locations, and events",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
