// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns paginated list of events with optional filters for site, surface, date range, and claim status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Get paginated events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Items per page (default: 10, max: 100)",
                        "name": "perPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by site name",
                        "name": "site",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by surface ID",
                        "name": "surface_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Export as CSV when present (any non-empty value)",
                        "name": "export",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by claim status (success or error)",
                        "name": "claim_status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventsResult"
                        }
                    },
                    "400": {
                        "description": "Invalid claim_status value",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the surface_id (and location_id) for a single event or all future events at the same location",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Update event surface assignment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event update parameters",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateEventInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event or Surface not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/gamesheet-seasons": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Fetches seasons from the Gamesheet API or a CSV file, and filters out inactive or expired seasons",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gamesheet"
                ],
                "summary": "Get active gamesheet seasons",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source of seasons: api (default) or csv",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Exclude seasons already stored in the local gamesheet_seasons table",
                        "name": "exclude_existing",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Season"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gamesheet-seasons/import": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Accepts an array of Season objects and inserts them into gamesheet_seasons and sites_config tables within a single transaction. Skips records that already exist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gamesheet"
                ],
                "summary": "Import gamesheet seasons",
                "parameters": [
                    {
                        "description": "Array of seasons to import",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Season"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Number of seasons imported",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/kmaster-venues": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a paginated list of all venues from the kmaster venue list. Use export=json to download all records as a JSON file (limited fields + LiveBarn surfaces). Use export=csv to download all records as a CSV file (all fields). No pagination for exports.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KmasterVenue"
                ],
                "summary": "List kmaster venues",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 10, max 100)",
                        "name": "perPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by country",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by province/state",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by venue name (partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by livebarn venue match status",
                        "name": "livebarn",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Export format: 'json' for JSON file download (limited fields + LiveBarn surfaces), 'csv' for CSV file download (all fields). No pagination for exports.",
                        "name": "export",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Downloaded venue list as kmaster-venues-{timestamp}.csv",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new venue record in the kmaster venue list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KmasterVenue"
                ],
                "summary": "Create kmaster venue",
                "parameters": [
                    {
                        "description": "Venue data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KmasterVenueListInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.KmasterVenueListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/kmaster-venues/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a single venue record from the kmaster venue list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KmasterVenue"
                ],
                "summary": "Get kmaster venue by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KmasterVenueListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Venue not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates an existing venue record in the kmaster venue list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KmasterVenue"
                ],
                "summary": "Update kmaster venue",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated venue data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KmasterVenueListInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KmasterVenueListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Venue not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes a venue record from the kmaster venue list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KmasterVenue"
                ],
                "summary": "Delete kmaster venue",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Venue not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/locations/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a LiveBarn location with its associated surfaces",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Locations"
                ],
                "summary": "Get LiveBarn location by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Location ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.LocationWithSurfaces"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Location not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/mhr-lb-notes": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the lb_notes field for a specific MHR location",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Update LiveBarn notes for MHR location",
                "parameters": [
                    {
                        "description": "MHR ID and LiveBarn notes",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.SetMhrLbNotesInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mhr-lb-notes/{mhr_id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves the lb_notes field for a specific MHR location",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Get LiveBarn notes for MHR location",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "MHR location ID",
                        "name": "mhr_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "LiveBarn notes",
                        "schema": {
                            "$ref": "#/definitions/main.GetMhrLbNotesResponse"
                        }
                    },
                    "404": {
                        "description": "MHR location not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mhr-locations": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns paginated MHR location mappings with optional filters. Include export query parameter to download CSV.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Get paginated MHR location mappings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Items per page (default: 10, max: 100)",
                        "name": "perPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by rink name (partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by province (partial match)",
                        "name": "province",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by LiveBarn location mapping status (0 for unmapped, 1 for mapped)",
                        "name": "livebarn_location_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort column (mhr_id, created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc, desc)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Export as CSV when present (any non-empty value)",
                        "name": "export",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MHRLocResult"
                        }
                    }
                }
            }
        },
        "/mhr-locations/{mhr_id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a single MHR location with its LiveBarn location and surface associations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Get MHR location by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "MHR location ID",
                        "name": "mhr_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MhrLocation"
                        }
                    },
                    "400": {
                        "description": "Invalid MHR ID format",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "MHR location not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/scrape": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Starts scraping for specified site or all enabled sites. Sites already being scraped are skipped. Returns 409 only if ALL requested sites are already running.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraping"
                ],
                "summary": "Trigger scraping for site(s)",
                "parameters": [
                    {
                        "description": "Scraping request parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ScrapeRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted, returns job status with sites_started and optionally sites_skipped",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "All requested sites are already being scraped",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/scrape/status": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns current scraping status for all configured sites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraping"
                ],
                "summary": "Get scraping status for all sites",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.ScrapeStatus"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/scrape/status/{site}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns current scraping status for the specified site",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraping"
                ],
                "summary": "Get scraping status for a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site name",
                        "name": "site",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScrapeStatus"
                        }
                    },
                    "404": {
                        "description": "Site not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/site-locations": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns paginated site location mappings for a given site with optional pagination parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Get paginated site location mappings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site name",
                        "name": "site",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter locations starting with this value",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Items per page (default: 10, max: 100)",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SiteLocResult"
                        }
                    }
                }
            }
        },
        "/sites-config": {
            "get": {
                "description": "Returns all site configurations with optional enabled filter, text search, and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SitesConfig"
                ],
                "summary": "List sites configurations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by enabled status (true/false)",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by site name or display name (partial match)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort column (site_name, display_name, last_scraped_at, games_scraped, games_imported, readiness_status)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc, desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SitesConfigResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/sites-config/{id}/readiness": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the readiness status (0=pending, 1=in progress, 2=ready) for a site configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SitesConfig"
                ],
                "summary": "Update site readiness status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site Config ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Readiness status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SitesConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid readiness status",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Site config not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/sites-config/{id}/toggle": {
            "post": {
                "description": "Toggles the enabled status of a site configuration. If enabled is NULL, sets to true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SitesConfig"
                ],
                "summary": "Toggle site configuration enabled status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site Config ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SitesConfigResponse"
                        }
                    },
                    "404": {
                        "description": "Site config not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.GetMhrLbNotesResponse": {
            "type": "object",
            "properties": {
                "lb_notes": {
                    "type": "string"
                },
                "mhr_id": {
                    "type": "integer"
                }
            }
        },
        "main.LocationWithSurfaces": {
            "type": "object",
            "properties": {
                "address1": {
                    "type": "string"
                },
                "address2": {
                    "type": "string"
                },
                "all_sheets_count": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "logo_url": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province_id": {
                    "type": "integer"
                },
                "recording_hours_local": {
                    "type": "string"
                },
                "surfaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Surface"
                    }
                },
                "total_surfaces": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                },
                "venue_status": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "main.ScrapeRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "Date in YYYY-MM-DD format (optional)",
                    "type": "string"
                },
                "site": {
                    "description": "Site name (empty for all enabled sites)",
                    "type": "string"
                },
                "workers": {
                    "description": "Number of workers (optional, default 1)",
                    "type": "integer"
                }
            }
        },
        "main.ScrapeStatus": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message if failed",
                    "type": "string"
                },
                "is_due_for_scraping": {
                    "description": "Whether site is due for scraping",
                    "type": "boolean"
                },
                "last_scraped_at": {
                    "description": "From sites_config",
                    "type": "string"
                },
                "readiness_status": {
                    "description": "0=pending, 1=in progress, 2=ready",
                    "type": "integer"
                },
                "scrape_frequency": {
                    "description": "Frequency in hours",
                    "type": "integer"
                },
                "site": {
                    "type": "string"
                },
                "started_at": {
                    "description": "When scraping started",
                    "type": "string"
                },
                "status": {
                    "description": "idle, running, completed, failed",
                    "type": "string"
                }
            }
        },
        "main.Season": {
            "type": "object",
            "properties": {
                "age_category": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "end": {
                    "type": "string"
                },
                "game_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "leagueId": {
                    "type": "integer"
                },
                "start": {
                    "type": "string"
                },
                "state_province": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "main.SetMhrLbNotesInput": {
            "type": "object",
            "required": [
                "mhr_id"
            ],
            "properties": {
                "lb_notes": {
                    "type": "string"
                },
                "mhr_id": {
                    "type": "integer"
                }
            }
        },
        "main.UpdateEventInput": {
            "type": "object",
            "properties": {
                "surface_id": {
                    "type": "integer"
                },
                "update_future": {
                    "type": "boolean"
                }
            }
        },
        "model.Location": {
            "type": "object",
            "properties": {
                "address1": {
                    "type": "string"
                },
                "address2": {
                    "type": "string"
                },
                "all_sheets_count": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "logo_url": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province_id": {
                    "type": "integer"
                },
                "recording_hours_local": {
                    "type": "string"
                },
                "total_surfaces": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                },
                "venue_status": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "model.Surface": {
            "type": "object",
            "properties": {
                "closed_from": {
                    "type": "integer"
                },
                "coming_soon": {
                    "type": "boolean"
                },
                "first_media_date": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "location_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "orderIndex": {
                    "type": "integer"
                },
                "sports": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "venue_id": {
                    "type": "integer"
                }
            }
        },
        "models.EventWithClaim": {
            "type": "object",
            "properties": {
                "claim_created_at": {
                    "type": "string"
                },
                "claim_error_message": {
                    "type": "string"
                },
                "claim_http_status_code": {
                    "type": "integer"
                },
                "claim_status": {
                    "type": "integer"
                },
                "claim_updated_at": {
                    "type": "string"
                },
                "date_created": {
                    "type": "string"
                },
                "datetime": {
                    "type": "string"
                },
                "division": {
                    "type": "string"
                },
                "edate": {
                    "type": "string"
                },
                "event_id": {
                    "type": "string"
                },
                "guest_team": {
                    "type": "string"
                },
                "home_team": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "location_id": {
                    "type": "integer"
                },
                "mhr_location_id": {
                    "type": "integer"
                },
                "oid_guest": {
                    "type": "string"
                },
                "oid_home": {
                    "type": "string"
                },
                "site": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "surface_id": {
                    "type": "integer"
                }
            }
        },
        "models.EventsResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EventWithClaim"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.KVenueResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KmasterVenueListResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.KmasterVenueExportItem": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "livebarn_venue_id": {
                    "type": "integer"
                },
                "mhr_venue_id": {
                    "type": "integer"
                },
                "province_state": {
                    "type": "string"
                },
                "surfaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KmasterVenueExportSurface"
                    }
                },
                "venue_name": {
                    "type": "string"
                }
            }
        },
        "models.KmasterVenueExportResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KmasterVenueExportItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.KmasterVenueExportSurface": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.KmasterVenueListInput": {
            "type": "object",
            "required": [
                "venue_name"
            ],
            "properties": {
                "account_status": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "company_name_alt1": {
                    "type": "string"
                },
                "company_name_alt2": {
                    "type": "string"
                },
                "company_name_alt3": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "livebarn_venue_id": {
                    "type": "integer"
                },
                "mhr_venue_id": {
                    "type": "integer"
                },
                "parent_company": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province_state": {
                    "type": "string"
                },
                "rink_address": {
                    "type": "string"
                },
                "streaming_platform": {
                    "type": "string"
                },
                "surfaces": {
                    "type": "integer"
                },
                "validate": {
                    "type": "integer"
                },
                "venue_name": {
                    "type": "string"
                },
                "venue_type": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "models.KmasterVenueListResponse": {
            "type": "object",
            "properties": {
                "account_status": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "company_name_alt1": {
                    "type": "string"
                },
                "company_name_alt2": {
                    "type": "string"
                },
                "company_name_alt3": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "livebarn_venue_id": {
                    "type": "integer"
                },
                "livebarn_venue_id_matched": {
                    "type": "boolean"
                },
                "mhr_venue_id": {
                    "type": "integer"
                },
                "mhr_venue_id_matched": {
                    "type": "boolean"
                },
                "parent_company": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province_state": {
                    "type": "string"
                },
                "rink_address": {
                    "type": "string"
                },
                "streaming_platform": {
                    "type": "string"
                },
                "surfaces": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "validate": {
                    "type": "integer"
                },
                "venue_name": {
                    "type": "string"
                },
                "venue_type": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "models.MHRLocResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MhrLocation"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.MhrLocation": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "aka": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "home_teams": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                },
                "lb_notes": {
                    "type": "string"
                },
                "linkedSurface": {
                    "$ref": "#/definitions/model.Surface"
                },
                "liveBarnLocation": {
                    "$ref": "#/definitions/model.Location"
                },
                "livebarn_installed": {
                    "type": "boolean"
                },
                "livebarn_location_id": {
                    "type": "integer"
                },
                "livebarn_surface_id": {
                    "type": "integer"
                },
                "mhr_id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "rink_name": {
                    "type": "string"
                },
                "streaming": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "models.SiteLoc": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "linkedSurface": {
                    "$ref": "#/definitions/model.Surface"
                },
                "liveBarnLocation": {
                    "$ref": "#/definitions/model.Location"
                },
                "location": {
                    "type": "string"
                },
                "location_id": {
                    "type": "integer"
                },
                "match_type": {
                    "type": "string"
                },
                "scraping_error": {
                    "type": "string"
                },
                "scraping_started_at": {
                    "type": "string"
                },
                "scraping_status": {
                    "type": "string"
                },
                "site": {
                    "type": "string"
                },
                "surface": {
                    "type": "string"
                },
                "surface_id": {
                    "type": "integer"
                }
            }
        },
        "models.SiteLocResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SiteLoc"
                    }
                },
                "events_matched": {
                    "type": "integer"
                },
                "games_claimed": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.SitesConfigResponse": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "games_imported": {
                    "type": "integer"
                },
                "games_scraped": {
                    "type": "integer"
                },
                "home_team": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_scraped_at": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "parser_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "parser_type": {
                    "type": "string"
                },
                "readiness_status": {
                    "type": "integer"
                },
                "scrape_frequency_hours": {
                    "type": "integer"
                },
                "scraping_error": {
                    "type": "string"
                },
                "scraping_started_at": {
                    "type": "string"
                },
                "scraping_status": {
                    "type": "string"
                },
                "site_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "gosession",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Surface API",
	Description:      "API for managing hockey rink schedules, surfaces, locations, and events",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
