// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/site-locations": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns paginated site location mappings for a given site with optional pagination parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Get paginated site location mappings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site name",
                        "name": "site",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter locations starting with this value",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Items per page (default: 10, max: 100)",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SiteLocResult"
                        }
                    }
                }
            }
        },
        "/sites-config/{id}/toggle": {
            "post": {
                "description": "Toggles the enabled status of a site configuration. If enabled is NULL, sets to true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SitesConfig"
                ],
                "summary": "Toggle site configuration enabled status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site Config ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SitesConfigResponse"
                        }
                    },
                    "404": {
                        "description": "Site config not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Location": {
            "type": "object",
            "properties": {
                "address1": {
                    "type": "string"
                },
                "address2": {
                    "type": "string"
                },
                "all_sheets_count": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "logo_url": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province_id": {
                    "type": "integer"
                },
                "recording_hours_local": {
                    "type": "string"
                },
                "total_surfaces": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                },
                "venue_status": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "model.Surface": {
            "type": "object",
            "properties": {
                "closed_from": {
                    "type": "integer"
                },
                "coming_soon": {
                    "type": "boolean"
                },
                "first_media_date": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "location_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "orderIndex": {
                    "type": "integer"
                },
                "sports": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "venue_id": {
                    "type": "integer"
                }
            }
        },
        "models.SiteLoc": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "linkedSurface": {
                    "$ref": "#/definitions/model.Surface"
                },
                "liveBarnLocation": {
                    "$ref": "#/definitions/model.Location"
                },
                "location": {
                    "type": "string"
                },
                "location_id": {
                    "type": "integer"
                },
                "match_type": {
                    "type": "string"
                },
                "site": {
                    "type": "string"
                },
                "surface": {
                    "type": "string"
                },
                "surface_id": {
                    "type": "integer"
                }
            }
        },
        "models.SiteLocResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SiteLoc"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.SitesConfigResponse": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "games_scraped": {
                    "type": "integer"
                },
                "home_team": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_scraped_at": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "parser_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "parser_type": {
                    "type": "string"
                },
                "scrape_frequency_hours": {
                    "type": "integer"
                },
                "site_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "gosession",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Surface API",
	Description:      "API for managing hockey rink schedules, surfaces, locations, and events",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
