// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"calendar-scrapper/dao/model"
)

func newVenueStatus(db *gorm.DB, opts ...gen.DOOption) venueStatus {
	_venueStatus := venueStatus{}

	_venueStatus.venueStatusDo.UseDB(db, opts...)
	_venueStatus.venueStatusDo.UseModel(&model.VenueStatus{})

	tableName := _venueStatus.venueStatusDo.TableName()
	_venueStatus.ALL = field.NewAsterisk(tableName)
	_venueStatus.ID = field.NewInt32(tableName, "id")
	_venueStatus.VenueStatusName = field.NewString(tableName, "venue_status_name")

	_venueStatus.fillFieldMap()

	return _venueStatus
}

type venueStatus struct {
	venueStatusDo venueStatusDo

	ALL             field.Asterisk
	ID              field.Int32
	VenueStatusName field.String

	fieldMap map[string]field.Expr
}

func (v venueStatus) Table(newTableName string) *venueStatus {
	v.venueStatusDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v venueStatus) As(alias string) *venueStatus {
	v.venueStatusDo.DO = *(v.venueStatusDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *venueStatus) updateTableName(table string) *venueStatus {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt32(table, "id")
	v.VenueStatusName = field.NewString(table, "venue_status_name")

	v.fillFieldMap()

	return v
}

func (v *venueStatus) WithContext(ctx context.Context) *venueStatusDo {
	return v.venueStatusDo.WithContext(ctx)
}

func (v venueStatus) TableName() string { return v.venueStatusDo.TableName() }

func (v venueStatus) Alias() string { return v.venueStatusDo.Alias() }

func (v venueStatus) Columns(cols ...field.Expr) gen.Columns { return v.venueStatusDo.Columns(cols...) }

func (v *venueStatus) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *venueStatus) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 2)
	v.fieldMap["id"] = v.ID
	v.fieldMap["venue_status_name"] = v.VenueStatusName
}

func (v venueStatus) clone(db *gorm.DB) venueStatus {
	v.venueStatusDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v venueStatus) replaceDB(db *gorm.DB) venueStatus {
	v.venueStatusDo.ReplaceDB(db)
	return v
}

type venueStatusDo struct{ gen.DO }

func (v venueStatusDo) Debug() *venueStatusDo {
	return v.withDO(v.DO.Debug())
}

func (v venueStatusDo) WithContext(ctx context.Context) *venueStatusDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v venueStatusDo) ReadDB() *venueStatusDo {
	return v.Clauses(dbresolver.Read)
}

func (v venueStatusDo) WriteDB() *venueStatusDo {
	return v.Clauses(dbresolver.Write)
}

func (v venueStatusDo) Session(config *gorm.Session) *venueStatusDo {
	return v.withDO(v.DO.Session(config))
}

func (v venueStatusDo) Clauses(conds ...clause.Expression) *venueStatusDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v venueStatusDo) Returning(value interface{}, columns ...string) *venueStatusDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v venueStatusDo) Not(conds ...gen.Condition) *venueStatusDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v venueStatusDo) Or(conds ...gen.Condition) *venueStatusDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v venueStatusDo) Select(conds ...field.Expr) *venueStatusDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v venueStatusDo) Where(conds ...gen.Condition) *venueStatusDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v venueStatusDo) Order(conds ...field.Expr) *venueStatusDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v venueStatusDo) Distinct(cols ...field.Expr) *venueStatusDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v venueStatusDo) Omit(cols ...field.Expr) *venueStatusDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v venueStatusDo) Join(table schema.Tabler, on ...field.Expr) *venueStatusDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v venueStatusDo) LeftJoin(table schema.Tabler, on ...field.Expr) *venueStatusDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v venueStatusDo) RightJoin(table schema.Tabler, on ...field.Expr) *venueStatusDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v venueStatusDo) Group(cols ...field.Expr) *venueStatusDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v venueStatusDo) Having(conds ...gen.Condition) *venueStatusDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v venueStatusDo) Limit(limit int) *venueStatusDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v venueStatusDo) Offset(offset int) *venueStatusDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v venueStatusDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *venueStatusDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v venueStatusDo) Unscoped() *venueStatusDo {
	return v.withDO(v.DO.Unscoped())
}

func (v venueStatusDo) Create(values ...*model.VenueStatus) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v venueStatusDo) CreateInBatches(values []*model.VenueStatus, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v venueStatusDo) Save(values ...*model.VenueStatus) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v venueStatusDo) First() (*model.VenueStatus, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VenueStatus), nil
	}
}

func (v venueStatusDo) Take() (*model.VenueStatus, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VenueStatus), nil
	}
}

func (v venueStatusDo) Last() (*model.VenueStatus, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VenueStatus), nil
	}
}

func (v venueStatusDo) Find() ([]*model.VenueStatus, error) {
	result, err := v.DO.Find()
	return result.([]*model.VenueStatus), err
}

func (v venueStatusDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VenueStatus, err error) {
	buf := make([]*model.VenueStatus, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v venueStatusDo) FindInBatches(result *[]*model.VenueStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v venueStatusDo) Attrs(attrs ...field.AssignExpr) *venueStatusDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v venueStatusDo) Assign(attrs ...field.AssignExpr) *venueStatusDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v venueStatusDo) Joins(fields ...field.RelationField) *venueStatusDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v venueStatusDo) Preload(fields ...field.RelationField) *venueStatusDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v venueStatusDo) FirstOrInit() (*model.VenueStatus, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VenueStatus), nil
	}
}

func (v venueStatusDo) FirstOrCreate() (*model.VenueStatus, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VenueStatus), nil
	}
}

func (v venueStatusDo) FindByPage(offset int, limit int) (result []*model.VenueStatus, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v venueStatusDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v venueStatusDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v venueStatusDo) Delete(models ...*model.VenueStatus) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *venueStatusDo) withDO(do gen.Dao) *venueStatusDo {
	v.DO = *do.(*gen.DO)
	return v
}
