CREATE TABLE api_keys (
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    key_hash   VARCHAR(64)  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    active     TINYINT(1)   NOT NULL DEFAULT 1,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX idx_key_hash (key_hash)
);
