CREATE TABLE IF NOT EXISTS `spordle_surfaces` (
  `id`                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `venue_id`                VARCHAR(36)     NOT NULL,
  `venue_name`              VARCHAR(255)    NOT NULL,
  `venue_address`           VARCHAR(255)    DEFAULT NULL,
  `venue_city`              VARCHAR(128)    DEFAULT NULL,
  `venue_region`            VARCHAR(64)     DEFAULT NULL,
  `venue_country`           VARCHAR(64)     DEFAULT NULL,
  `venue_alias`             VARCHAR(255)    DEFAULT NULL,
  `venue_latitude`          DECIMAL(10,7)   DEFAULT NULL,
  `venue_longitude`         DECIMAL(10,7)   DEFAULT NULL,
  `venue_postal_code`       VARCHAR(20)     DEFAULT NULL,
  `surface_id`              INT UNSIGNED    NOT NULL,
  `surface_name`            VARCHAR(255)    NOT NULL,
  `surface_alias`           VARCHAR(255)    DEFAULT NULL,
  `surface_sports`          VARCHAR(255)    DEFAULT NULL COMMENT 'JSON array string, e.g. ["Hockey"]',
  `surface_time_zone`       VARCHAR(64)     DEFAULT NULL,
  `surface_type`            VARCHAR(64)     DEFAULT NULL COMMENT 'Ice, Grass, Synthetic, Gym, etc.',
  `surface_size`            VARCHAR(8)      DEFAULT NULL COMMENT 'XS, S, M, L, XL',
  `livebarn_surface_id`     VARCHAR(64)     DEFAULT NULL,
  `number_of_games_coming`  INT             DEFAULT NULL,
  `created_at`              datetime        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`              datetime        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_spordle_surfaces_venue_surface` (`venue_id`, `surface_id`),
  KEY `idx_spordle_surfaces_surface_id` (`surface_id`),
  KEY `idx_spordle_surfaces_venue_id` (`venue_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
