CREATE TABLE kmaster_venue_list (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  validate TINYINT NOT NULL DEFAULT 0,
  livebarn_venue_id INT DEFAULT NULL,
  mhr_venue_id INT DEFAULT NULL,
  venue_name VARCHAR(255) NOT NULL,
  surfaces INT NOT NULL DEFAULT 0,
  city VARCHAR(255) DEFAULT NULL,
  rink_address VARCHAR(255) DEFAULT NULL,
  postal_code VARCHAR(20) DEFAULT NULL,
  province_state VARCHAR(10) DEFAULT NULL,
  country VARCHAR(10) DEFAULT NULL,
  company_name_alt1 VARCHAR(255) DEFAULT NULL,
  company_name_alt2 VARCHAR(255) DEFAULT NULL,
  company_name_alt3 VARCHAR(255) DEFAULT NULL,
  parent_company VARCHAR(255) DEFAULT NULL,
  venue_type VARCHAR(255) DEFAULT NULL,
  account_status VARCHAR(255) DEFAULT NULL,
  streaming_platform VARCHAR(255) DEFAULT NULL,
  phone_number VARCHAR(100) DEFAULT NULL,
  website VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_livebarn_venue_id (livebarn_venue_id),
  INDEX idx_mhr_venue_id (mhr_venue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
