// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameGamesheetSeason = "gamesheet_seasons"

// GamesheetSeason mapped from table <gamesheet_seasons>
type GamesheetSeason struct {
	ID        uint32     `gorm:"column:id;primaryKey" json:"id"`
	Title     string     `gorm:"column:title" json:"title"`
	LeagueID  uint32     `gorm:"column:league_id" json:"league_id"`
	IsActive  int8       `gorm:"column:is_active;default:0" json:"is_active"`
	StartDate *time.Time `gorm:"column:start_date" json:"start_date"`
	EndDate   *time.Time `gorm:"column:end_date" json:"end_date"`
}

// TableName GamesheetSeason's table name
func (*GamesheetSeason) TableName() string {
	return TableNameGamesheetSeason
}
