// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMhrSheet = "mhr_sheet"

// MhrSheet mapped from table <mhr_sheet>
type MhrSheet struct {
	ID                int32  `gorm:"column:id;primaryKey" json:"id"`
	RinkName          string `gorm:"column:rink_name;not null" json:"rink_name"`
	LivebarnInstalled int32  `gorm:"column:livebarn_installed" json:"livebarn_installed"`
	LivebarnVenueID   int32  `gorm:"column:livebarn_venue_id" json:"livebarn_venue_id"`
	RinkType          string `gorm:"column:rink_type" json:"rink_type"`
	AltName           string `gorm:"column:alt_name" json:"alt_name"`
	AltName2          string `gorm:"column:alt_name2" json:"alt_name2"`
	AltName3          string `gorm:"column:alt_name3" json:"alt_name3"`
	RinkPads          int32  `gorm:"column:rink_pads" json:"rink_pads"`
	City              string `gorm:"column:city;not null" json:"city"`
	State             string `gorm:"column:state;not null" json:"state"`
	Address           string `gorm:"column:address" json:"address"`
	Zip               string `gorm:"column:zip" json:"zip"`
	Country           string `gorm:"column:country" json:"country"`
	Phone             string `gorm:"column:phone" json:"phone"`
}

// TableName MhrSheet's table name
func (*MhrSheet) TableName() string {
	return TableNameMhrSheet
}
