// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSitesConfig = "sites_config"

// SitesConfig Configuration for dynamically scraped sites
type SitesConfig struct {
	ID                   int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SiteName             string    `gorm:"column:site_name;not null;comment:Unique site identifier" json:"site_name"`                                    // Unique site identifier
	DisplayName          string    `gorm:"column:display_name;comment:Human-readable site name" json:"display_name"`                                     // Human-readable site name
	BaseURL              string    `gorm:"column:base_url;not null;comment:Base URL for the site" json:"base_url"`                                       // Base URL for the site
	HomeTeam             string    `gorm:"column:home_team;comment:Home team name for the site" json:"home_team"`                                        // Home team name for the site
	ParserType           string    `gorm:"column:parser_type;not null;comment:Type of parser to use" json:"parser_type"`                                 // Type of parser to use
	ParserConfig         string    `gorm:"column:parser_config;comment:Parser-specific configuration in JSON format" json:"parser_config"`               // Parser-specific configuration in JSON format
	Enabled              bool      `gorm:"column:enabled;default:1;comment:Whether site scraping is enabled" json:"enabled"`                             // Whether site scraping is enabled
	LastScrapedAt        time.Time `gorm:"column:last_scraped_at;comment:Last successful scrape timestamp" json:"last_scraped_at"`                       // Last successful scrape timestamp
	ScrapeFrequencyHours int32     `gorm:"column:scrape_frequency_hours;default:24;comment:Minimum hours between scrapes" json:"scrape_frequency_hours"` // Minimum hours between scrapes
	Notes                string    `gorm:"column:notes;comment:Additional notes about the site" json:"notes"`                                            // Additional notes about the site
	CreatedAt            time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	GamesScraped         int32     `gorm:"column:games_scraped;not null" json:"games_scraped"`
	GamesImported        int32     `gorm:"column:games_imported;not null" json:"games_imported"`
	ScrapingStatus       string    `gorm:"column:scraping_status;default:idle;comment:Current scraping status" json:"scraping_status"` // Current scraping status
	ScrapingStartedAt    time.Time `gorm:"column:scraping_started_at;comment:When scraping started" json:"scraping_started_at"`        // When scraping started
	ScrapingError        string    `gorm:"column:scraping_error;comment:Error message if scraping failed" json:"scraping_error"`       // Error message if scraping failed
}

// TableName SitesConfig's table name
func (*SitesConfig) TableName() string {
	return TableNameSitesConfig
}
