// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameSitesTag = "sites_tags"

// SitesTag mapped from table <sites_tags>
type SitesTag struct {
	SiteName  string    `gorm:"column:site_name;primaryKey" json:"site_name"`
	TagID     int32     `gorm:"column:tag_id;primaryKey" json:"tag_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName SitesTag's table name
func (*SitesTag) TableName() string {
	return TableNameSitesTag
}
