// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSitesLocation = "sites_locations"

// SitesLocation mapped from table <sites_locations>
type SitesLocation struct {
	Site       string `gorm:"column:site;primaryKey" json:"site"`
	Location   string `gorm:"column:location;primaryKey" json:"location"`
	LocationID int32  `gorm:"column:location_id" json:"location_id"`
}

// TableName SitesLocation's table name
func (*SitesLocation) TableName() string {
	return TableNameSitesLocation
}
