// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVenueStatus = "venue_status"

// VenueStatus mapped from table <venue_status>
type VenueStatus struct {
	ID              int32  `gorm:"column:id;primaryKey" json:"id"`
	VenueStatusName string `gorm:"column:venue_status_name;not null" json:"venue_status_name"`
}

// TableName VenueStatus's table name
func (*VenueStatus) TableName() string {
	return TableNameVenueStatus
}
