// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGamesheetSchedule = "gamesheet_schedules"

// GamesheetSchedule mapped from table <gamesheet_schedules>
type GamesheetSchedule struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SeasonID  int32     `gorm:"column:season_id;not null" json:"season_id"`
	GameData  string    `gorm:"column:game_data;not null" json:"game_data"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GamesheetSchedule's table name
func (*GamesheetSchedule) TableName() string {
	return TableNameGamesheetSchedule
}
