// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGamesheetSeason = "gamesheet_seasons"

// GamesheetSeason mapped from table <gamesheet_seasons>
type GamesheetSeason struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	Title     string    `gorm:"column:title" json:"title"`
	Site      string    `gorm:"column:site;not null" json:"site"`
	LeagueID  int32     `gorm:"column:league_id" json:"league_id"`
	IsActive  int32     `gorm:"column:is_active" json:"is_active"`
	StartDate time.Time `gorm:"column:start_date" json:"start_date"`
	EndDate   time.Time `gorm:"column:end_date" json:"end_date"`
}

// TableName GamesheetSeason's table name
func (*GamesheetSeason) TableName() string {
	return TableNameGamesheetSeason
}
