// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRAMPLocation = "RAMP_Locations"

// RAMPLocation mapped from table <RAMP_Locations>
type RAMPLocation struct {
	RARID        int32  `gorm:"column:RARID;primaryKey" json:"RARID"`
	Name         string `gorm:"column:name" json:"name"`
	Abbr         string `gorm:"column:abbr" json:"abbr"`
	Address      string `gorm:"column:address" json:"address"`
	City         string `gorm:"column:city" json:"city"`
	Prov         string `gorm:"column:prov" json:"prov"`
	ProvinceName string `gorm:"column:province_name" json:"province_name"`
	Pcode        string `gorm:"column:pcode" json:"pcode"`
	Country      string `gorm:"column:country" json:"country"`
	Phone        string `gorm:"column:phone" json:"phone"`
	LiveBarnID   string `gorm:"column:liveBarnId" json:"liveBarnId"`
	Loc          string `gorm:"column:loc" json:"loc"`
	LocationID   int32  `gorm:"column:location_id;not null" json:"location_id"`
	MatchType    string `gorm:"column:match_type" json:"match_type"`
	SurfaceID    int32  `gorm:"column:surface_id" json:"surface_id"`
}

// TableName RAMPLocation's table name
func (*RAMPLocation) TableName() string {
	return TableNameRAMPLocation
}
