// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSession = "session"

// Session mapped from table <session>
type Session struct {
	SessionKey    string `gorm:"column:session_key;primaryKey" json:"session_key"`
	SessionData   []byte `gorm:"column:session_data" json:"session_data"`
	SessionExpiry int32  `gorm:"column:session_expiry;not null" json:"session_expiry"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
