// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameSitesLocationTag = "sites_location_tags"

// SitesLocationTag mapped from table <sites_location_tags>
type SitesLocationTag struct {
	Site      string    `gorm:"column:site;primaryKey" json:"site"`
	Location  string    `gorm:"column:location;primaryKey" json:"location"`
	TagID     int32     `gorm:"column:tag_id;primaryKey" json:"tag_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName SitesLocationTag's table name
func (*SitesLocationTag) TableName() string {
	return TableNameSitesLocationTag
}
